blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap


from .sitemaps import (StaticViewsSitemaps,
                       PostsViewsSitemap,
                       AuthorViewsSitemap,
                       CategoriesViewsSitemap)

sitemaps = {'static': StaticViewsSitemaps,
            'posts': PostsViewsSitemap,
            'author_posts': AuthorViewsSitemap,
            'cats': CategoriesViewsSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error/',TemplateView.as_view(template_name='404.html')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path(r'tinymce/', include('tinymce.urls')),
    path('mailchimp/', include('marketing.urls', namespace='mailchimp')),
    path('<slug:post_slug>/comments/',
         include('comments.urls', namespace='comments')),
    path('post-<slug:slug>/comments-api/',
         include('comments.api.urls', namespace='comments-api')),
    path('posts/', include('posts.urls', namespace='posts')),
        path('', include('main.urls', namespace='main')),
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('search/', include('search.urls', namespace='search')),



    
  
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

main/urls.py
from django.urls import path
from .views import (
                    home_page_view, AboutMeView,
                    PostsDashboard,CategoriesDashboard,
                    AboutBlogView, PrivacyPolicyView, ContactUsView,
                    authors_admin_view,confirm_author_view,
                    )

app_name = 'main'
urlpatterns = [

    path('posts-dashboard/', PostsDashboard.as_view(), name='posts-dashboard'),
    path('categories-dashboard/', CategoriesDashboard.as_view(), name='categories-dashboard'),
    path('', home_page_view, name='home'),
    path('about_me', AboutMeView.as_view(), name='about_me'),
    path('about_blog', AboutBlogView.as_view(), name='about_blog'),
    path('privacy-policy', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('contact-us', ContactUsView.as_view(), name='contact_us')

    ]


urlpatterns += [
    path('authors_admin/', authors_admin_view, name='authors_admin'),


    path('confirm-author/<slug:slug>/',
         confirm_author_view, name='confirm_author')
]

posts/urls.py
from django.urls import path

from .views import (post_detail,posts_list_view, category_post_view, authors_post_view,
                    AddPostView, AddCategoryView, EditCategoryView, EditPostView, DeletePostView,
                    )

app_name = 'posts'
urlpatterns = [
    path('', posts_list_view, name='list'),
    path('add-post/', AddCategoryView.as_view(), name='add_category'),
    path('edit-category/<slug:slug>/',
         EditCategoryView.as_view(), name='edit_category'),
    path('add-category/', AddPostView.as_view(), name='add_post'),
    path('edit-post/<slug:post_slug>/', EditPostView.as_view(), name='edit_post'),
    path('delete-post/<slug:post_slug>/',
         DeletePostView.as_view(), name='delete_post'),
    path('<slug:slug>/', post_detail, name='detail'),
    path('categories/<slug:cat_slug>/posts',
         category_post_view, name='category_posts'),
    path('author/<slug:auth_slug>/posts',
         authors_post_view, name='author_posts'),
]

main/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import AboutMe, AboutBlog, PrivacyPolicy

class ContactForm(forms.Form):
    name = forms.CharField(label=_('name'),widget=forms.TextInput())
    email = forms.EmailField(label=_('email'),widget=forms.TextInput())
    subject = forms.CharField(label=_('subject'),widget=forms.TextInput())
    message = forms.CharField(label=_('message'),widget=forms.Textarea())

    

class AboutMeForm(forms.ModelForm):
    class Meta:
        model = AboutMe
        fields = ['overview', 'content']


class AboutBlogForm(forms.ModelForm):
    class Meta:
        model = AboutBlog
        fields = ['overview', 'content']


class PrivacyPolicyForm(forms.ModelForm):
    class Meta:
        model = PrivacyPolicy
        fields = ['overview', 'content']

posts/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from .models import Post,Category

from PIL import Image


# def thumbnail_validation(value):
#     img = Image.open(value)
#     # if img.height != 450 and img.width != 800:
#     return value


class AddPostForm(forms.ModelForm):
    # thumbnail = forms.ImageField(validators=[thumbnail_validation])

    class Meta:
        labels = {'title':_('title'),'overview':_('overview'),
                  'content':_('content'),'thumbnail':_('thumbnail'),
                  'categories':_('categories'),'active':_('active'),
                  'featured':_('featured'),'notificated':_('notificated')}
        model = Post
        fields = ['title', 'overview', 'content',
                  'thumbnail', 'categories', 'active','notificated' ,'featured']
    

class AddCategoryForm(forms.ModelForm):
    class Meta:
        labels = {'title':_('title')}
        model = Category
        fields = ['title']

main/views.py
from django.shortcuts import render, reverse, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy, reverse
from django.conf import settings

from django.views.generic import (
        TemplateView, FormView, ListView,
        CreateView, UpdateView, DeleteView
        )
from django.views import generic

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.utils.translation import ugettext as _
from django.db.models import Q

from .forms import ContactForm

from posts.utils import date_capture
from posts.models import Post, Author, Category
from .models import AboutMe, AboutBlog, PrivacyPolicy,MianImage
from .mixins import AuthorRequiredMixin, AuthorCheckMixin,AdminRequiredMixin
from blog.decorators import super_user_only

from .forms import AboutBlogForm, AboutMeForm, PrivacyPolicyForm
import string


User = get_user_model()

def home_page_view(request):
    main_obj = MianImage.objects.last()
    featured_posts = Post.objects.featured()[:3].select_related('author__user',
                                                                'author__user__profileimage')
    latest_posts = Post.objects.all().prefetch_related('categories',)[:3]
    context = {'featured_posts': featured_posts,
               'latest_posts': latest_posts,
               'obj':main_obj
               
               }
    return render(request, 'main/home.html', context)



class AboutMeView(ListView):
    template_name = 'info/about_me.html'

    context_object_name = 'privacy'

    def get_queryset(self):
        qs = AboutMe.objects.all().last()
        return qs


class AboutBlogView(ListView):
    template_name = 'info/about_blog.html'

    context_object_name = 'about_blog'

    def get_queryset(self):
        qs = AboutBlog.objects.all().last()
        return qs


class PrivacyPolicyView(ListView):
    template_name = 'info/privacy_policy.html'
    context_object_name = 'privacy'

    def get_queryset(self):
        qs = PrivacyPolicy.objects.all().last()
        return qs


class ContactUsView(FormView):
    form_class = ContactForm
    template_name = 'info/contact_us.html'
    success_url = reverse_lazy('main:contact_us')

    def form_valid(self, form):
        subject = form.cleaned_data.get('name')
        from_email = form.cleaned_data.get('email')
        to_email = getattr(settings, 'DEFAULT_FROM_EMAIL')
        message = form.cleaned_data.get('message')
        context = {'name': subject, 'email': from_email, 'message': message, }
        txt_ = get_template('snippets/message.txt').render(context)
        html_ = get_template(
            'snippets/html_message.html').render(context)
        send_mail(
            subject,
            txt_,
            from_email,
            [to_email, ],
            html_message=html_,
            fail_silently=False
        )
        messages.add_message(self.request, messages.SUCCESS,
                             _('your message has been sent'))
        return redirect('main:contact_us')


class PostsDashboard(LoginRequiredMixin, AuthorRequiredMixin, generic.ListView):
    template_name = 'main/dashboards/posts.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 15

    def get_queryset(self):
        q = self.request.GET.get('q')    
        author = self.request.user.author
        
        if q:
            date, exists = date_capture(q)
            if exists:
                year, month, day = date.split('-')
                if int(year) == 0 or int(month) == 0 and int(day) == 0:
                    date = '2000-12-12'
            else:
                date = '2000-12-12'

            filters = Q(title__icontains=q) | Q(content__icontains=q) |Q(timestamp=date) | Q(slug__exact=q)
            qs = super().get_queryset().filter(author=author).filter(filters).order_by('slug')
        else:
            qs = super().get_queryset().filter(author=author).order_by('slug')
        return qs


class CategoriesDashboard(LoginRequiredMixin,generic.ListView):
    template_name = 'main/dashboards/categories.html'
    model = Category
    context_object_name = 'cates'


@login_required
@super_user_only
def authors_admin_view(request):
    page_var = 'page'
    page = request.GET.get(page_var, 1)
    
    current_page = User.objects.qs_paginator(page=page)

    context = {'page_obj': current_page,
               'page_var': page_var,
               }

    return render(request, 'main/authors_admin.html', context)


@login_required
@super_user_only
def confirm_author_view(request, slug):
    confirm = request.POST.get('confirm')
    status = request.POST.get('status', _('create'))
    username = User.objects.filter(slug=slug).values(
        'username').first()['username']

    if confirm:
        user = User.objects.filter(slug=slug).first()
        if user.is_author:
            status = _('deleted')
            author = Author.objects.filter(user__slug=slug).first().delete()
            user.is_author = False
            
        else:
            status = _('created')
            user.is_author = True
            author = Author.objects.create(user=user)        
        user.save()
        messages.add_message(request, messages.SUCCESS,
                             _('You have successfuly {} Author for {} ').format(status, username).upper())
        return redirect('main:authors_admin')
    return render(request, 'main/confirm_author.html', {"status": status, 'username': username})

posts/views.py
from django.shortcuts import (render,
                              get_object_or_404,
                              redirect)

from django.views import generic
from django.utils.translation import ugettext_lazy as _
from django.db.models import Q
from django.urls import reverse_lazy,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.contrib.messages.views import SuccessMessageMixin

from .forms import AddPostForm,AddCategoryForm
from .models import Post, Author, Category

from comments.forms import CommentForm

from main.mixins import AuthorRequiredMixin, AuthorCheckMixin
from main.models import (AboutBlog, AboutMe, PrivacyPolicy)

from urllib.parse import quote_plus


def posts_list_view(request):
    page = request.GET.get('page', 1)
    page_var = 'page'
    blog_var = True
    cates_num = Post.objects.categories_count()
    recent_posts = Post.objects.latest().select_related(
        'author__user').prefetch_related('comments')
    page_qy = Post.objects.qs_paginator(page=page)
    context = {

        'page_var': page_var,
        'page_obj': page_qy,
        'recent_posts': recent_posts,
        'cates_num': cates_num,
        'blog_var': blog_var,
    }
    return render(request, 'posts/list.html', context)


def post_detail(request, slug):
    comments_list_url = reverse('comments-api:list',kwargs={'slug':slug})
    qs = Post.objects.filter(slug=slug).select_related(
        'author__user__profileimage').prefetch_related('comments', 'categories')
    user = request.user
    if qs.count() == 1:
        post = qs.first()
        if post.active or user.is_admin or user.is_author:
            form = CommentForm()
            recent_posts = Post.objects.latest().select_related(
                'author__user').prefetch_related('comments')
            cates_num = Post.objects.categories_count()

            share_str = quote_plus(post.overview[:70] + '... ')
            share_title = quote_plus(post.title)

            try:
                previous_post = post.get_previous_by_timestamp()
            except:
                previous_post = None
            try:
                next_post = post.get_next_by_timestamp()
            except:
                next_post = None

        context = {'obj': post, 'recent_posts': recent_posts,
                   'comments_list_url':comments_list_url,
                   'form': form, 'cates_num': cates_num,
                   'previous': previous_post, 'next': next_post,
                   'share_str': share_str, 'share_title': share_title,}

        return render(request, 'posts/detail.html', context)

    raise Http404()


def category_post_view(request, cat_slug):
    page = request.GET.get('page', 1)
    page_var = 'page'
    filter = Q(categories__slug__icontains=cat_slug)
    cat = get_object_or_404(Category,slug=cat_slug)
    cat_posts = Post.objects.qs_paginator(page=page, filters=filter)
    

    context = {
        'page_obj': cat_posts,
        'page_var': page_var,
        'cat_name':cat.title

    }

    return render(request, 'posts/list.html', context)


def authors_post_view(request, auth_slug):
    author = get_object_or_404(Author, user__slug=auth_slug)

    page = request.GET.get('page', 1)
    page_var = 'page'
    filter = Q(author=author)
    auth_posts = Post.objects.qs_paginator(page=page, filters=filter)

    context = {
        'page_obj': auth_posts,
        'page_var': page_var,
    }
    return render(request, 'posts/list.html', context)


class AddPostView(LoginRequiredMixin, AuthorRequiredMixin, generic.CreateView):
    template_name = 'posts/create.html'
    form_class = AddPostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user = self.request.user
        author = Author.objects.filter(user=user).first()
        self.object.author = author
        self.object.save()
        return super().form_valid(form)


class EditPostView(LoginRequiredMixin, AuthorRequiredMixin, AuthorCheckMixin, generic.UpdateView):
    template_name = 'posts/create.html'
    model = Post
    form_class = AddPostForm
    slug_url_kwarg = 'post_slug'


class DeletePostView(SuccessMessageMixin,LoginRequiredMixin, AuthorRequiredMixin, AuthorCheckMixin, generic.DeleteView):
    template_name = 'posts/confirm_delete.html'
    model = Post
    slug_url_kwarg = 'post_slug'
    success_message = _('The post has been deleted')
    success_url = reverse_lazy('main:posts-dashboard')


class AddCategoryView(LoginRequiredMixin, AuthorRequiredMixin, generic.CreateView):
    queryset = Category.objects.all()
    form_class = AddCategoryForm
    template_name = 'posts/create_category.html'
    success_url = reverse_lazy('main:categories-dashboard')


class EditCategoryView(LoginRequiredMixin, AuthorRequiredMixin, generic.UpdateView):
    queryset = Category.objects.all()
    form_class = AddCategoryForm
    template_name = 'posts/create_category.html'
    success_url = reverse_lazy('main:categories-dashboard')

main/templates/main/dashboards/categories.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
  {% trans 'Categories Dashboard' %}
{% endblock %}
{% block  content %}
{% load static %}

<div class="container dash-board">
  <div class="row">
    <div class="col-md-7 m-auto auth text-center ">
      <h2 class="mt-5 mb-4 pb-3">
        {% trans 'Categories Dashboard' %}
        
      </h2>
    </div>

    <div class="col-md-10 m-auto">
      
      <p class="table-add-new">
           <a class="btn btn-link" href="{% url 'posts:add_category' %}">
            {% trans 'To add new Category' %}  
            <i class="fa fa-plus"></i>
          </a>
      </p>
    </div>
    <div class="col-md-10 m-auto">
      <br />
      {% if cates %}
      <table class="table">

        <thead class="thead-dark">
          <tr style="border-radius: 6px">
            <th scope="col">{% trans 'Title' %}</th>
            <th scope="col">{% trans 'Slug' %}</th>
            <th scope="col">{% trans 'Created At' %}</th>
            <th scope="col">

              ###
            </th>
          </tr>
        </thead>
        <tbody>
          {% for cate in cates %}
          <tr>
            <th scope="row">{{cate.title|capfirst}}</th>
            <th scope="row">{{cate.slug}}</th>
            <td>{{cate.timestamp}}</td>
            <td class="">
              <a href="{% url 'posts:edit_category' slug=cate.slug %}" class='btn'>
                {% trans 'Edit' %}
              </a>

            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
      {% else %}
      <p class="das-par text-center"> 
         {% trans ' There are no categories' %}
      </p>
      {% endif %}

    </div>

  </div>
</div>
{% endblock %}

main/templates/main/dashboards/posts.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
  {% trans 'Posts Dashboard' %}
{% endblock %}
{% block  content %}
{% load static %}

<div class="container dash-board">
  <div class="row">
    <div class="col-md-6 m-auto">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{message.level_tag}} alert-dismissible fade show" role="alert">
          <p{% if message.tags %} class="{{ message.tags }} text-center" {% endif %}>{{ message }}</p>
              {% endfor %}

              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>

      </div>
      {% endif %}
    </div>
    <div class="w-100"></div>
    <div class="col-md-6 auth m-auto  text-center">
      <h2 class="mt-5 mb-3 pb-3"> 
        {% trans 'Posts Dashboard' %}
      </h2>
    </div>
    <div class="w-100"></div>
    <div class="col-md-8 m-auto">
      <p class="lead table-add-new">
        <a class="btn btn-link" href="{% url 'posts:add_post' %}">
          <i class="fa fa-plus"></i> 
          {% trans 'To add new post' %}  
        </a>        
      </p>
    </div>
    <div class="col-md-8 m-auto">
      {% url 'main:posts-dashboard' as posts_url %}
      {% include 'snippets/search_bar_widget.html' with url=posts_url %}
    </div>
    <div class="col-md-10 m-auto">
      <br />
      {% if  posts %}
      <table class="table">

        <thead class="thead-dark">
          <tr style="border-radius: 6px">
            <th scope="col">
              {% trans 'Title' %}
            </th>

            <th scope="col">{% trans 'Slug' %}</th>
            <th scope="col">{% trans 'Created At' %}</th>
            <th scope="col">
              ###
            </th>
          </tr>
        </thead>
        <tbody>
          {% for post in posts %}
          <tr>
            <th scope="row">

              <a href="{{post.get_absolute_url}}">
                {{post.title|capfirst}}
              </a>
            </th>

            <td>{{post.slug}}</td>
            <td>{{post.timestamp}}</td>
            <td class="">
              <a href="{% url 'posts:edit_post' post_slug=post.slug %}" class='btn'>
                {% trans 'Edit' %}
              </a>

              <a href="{% url 'posts:delete_post' post_slug=post.slug %}" class='btn'>
                {% trans 'Delete' %}
              </a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
      <div>
        {% include 'snippets/paginator.html' with page_var="page" %}
      </div>
      {% else %}
      <p class="das-par text-center"> 
        {% trans 'There are no Posts' %} 
      </p>
      {% endif %}

    </div>

  </div>
</div>
{% endblock %}