blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap


from .sitemaps import (StaticViewsSitemaps,
                       PostsViewsSitemap,
                       AuthorViewsSitemap,
                       CategoriesViewsSitemap)

sitemaps = {'static': StaticViewsSitemaps,
            'posts': PostsViewsSitemap,
            'author_posts': AuthorViewsSitemap,
            'cats': CategoriesViewsSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error/',TemplateView.as_view(template_name='404.html')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path(r'tinymce/', include('tinymce.urls')),
    path('mailchimp/', include('marketing.urls', namespace='mailchimp')),
    path('<slug:post_slug>/comments/',
         include('comments.urls', namespace='comments')),
    path('post-<slug:slug>/comments-api/',
         include('comments.api.urls', namespace='comments-api')),
    path('posts/', include('posts.urls', namespace='posts')),
        path('', include('main.urls', namespace='main')),
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('search/', include('search.urls', namespace='search')),



    
  
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

comments/api/urls.py
from django.urls import path

from .views import (CommentListAPIView,AddCommentAPIView,EditCommentAPIView,
					DeleteCommentAPIView,AddReplyAPIView,EditReplyAPIView,
					DeleteReplyAPIView)

app_name = 'comments_api'

urlpatterns = [
	path('list/',CommentListAPIView.as_view(),name='list'),
	path('add/',AddCommentAPIView.as_view() ,name='add'),
	path('<int:pk>/edit/',EditCommentAPIView.as_view() ,name='edit'),
	path('<int:pk>/delete/',DeleteCommentAPIView.as_view() ,name='delete'),
	path('comment-<int:pk>/reply/add/',AddReplyAPIView.as_view() ,name='reply-add'),
	path('comment-<int:pk>/reply/<int:reply_id>/edit/',EditReplyAPIView.as_view() ,name='reply-edit'),
	path('comment-<int:pk>/reply/<int:reply_id>/delete/',DeleteReplyAPIView.as_view() ,name='reply-delete'),
	

]

comments/urls.py
from django.urls import path

app_name = 'commetns'

urlpatterns = [


]

comments/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from posts.models import Post

User = get_user_model()

class CommentManager(models.Manager):
	def all_real(self):
		return self.get_queryset()

class Comment(models.Model):
    user = models.ForeignKey(User,related_name='comments',on_delete=models.CASCADE,
                            null=True,blank=True)
    post = models.ForeignKey(Post,related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(null=True,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return str(self.user.username)

    objects = CommentManager()

class Reply(models.Model):
    user = models.ForeignKey(User,related_name='replies',on_delete=models.CASCADE,
                            null=True,blank=True)
    post = models.ForeignKey(Post,related_name='replies', on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment,related_name='replies',on_delete=models.CASCADE) 
    content = models.TextField(null=True,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name = _('Reply')
        verbose_name_plural = _('Replies')

    def __str__(self):
        return str(self.user.username)

    objects = CommentManager()

comments/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Comment


class CommentForm(forms.ModelForm):
    content = forms.CharField(label=_("Content"),
                              required=True,
                              widget=forms.Textarea(attrs={
    'name':"usercomment",
     'id':"usercomment",
     'placeholder':_(" Type your comment "),
     'class':"form-control",
     'rows':4,
    }))

    class Meta:
        model = Comment
        fields = ['content']

# class EditCommentForm(forms.ModelForm):
#     content = forms.CharField(label='',
#                               required=False,
#                               widget=forms.Textarea(attrs={
#     'name':"editform",
#      'id':"edit-form-field",
#      'placeholder':"Type your comment",
#      'class':"form-control",
#      'rows':3,
#     }))

#     class Meta:
#         model = Comment
#         fields = ['content']

# class ReplyForm(forms.ModelForm):
#     content = forms.CharField(label='Add Reply',required=False,widget=forms.Textarea(attrs={
#      'id':"reply-form-field",
#      'placeholder':"Type your reply",
#      'class':"form-control",
#      'rows':3,
#     }))

#     class Meta:
#         model = Reply
#         fields = ['content']

comments/api/views.py
from rest_framework.generics import (ListAPIView,CreateAPIView,
                                     UpdateAPIView,DestroyAPIView)
from rest_framework.views import APIView
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework import mixins
from rest_framework import generics
from rest_framework import status


from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext as _

# from .mixins import CommentContextMixin
from .permissions import (IsOwner,IsOwnerOrAdmin,
                          SameCommentPost,
                          SameCommentAndPost)
from .pagination import CommentsPagination
from .serializers import (CommentSerialzer,CommentAddSerialzer,
                          ReplyAddSerialzer,ReplySerializer)
from comments.models import Comment,Reply
from posts.models import Post


class CommentListAPIView(ListAPIView):
    serializer_class = CommentSerialzer
    pagination_class = CommentsPagination

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        qs = Comment.objects.filter(post__slug=slug)     
        return qs

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context.update({"request": self.request})
        return context        
    

class AddCommentAPIView(APIView):

    def post(self,request,*args,**kwargs):
        content = request.data.get('content')
        post = get_object_or_404(Post,slug=self.kwargs.get('slug'))
        user = request.user
        if user.is_authenticated:
            comment = CommentAddSerialzer(data={'content':content})
            if comment.is_valid() :
                obj = comment.save(post=post,user=user)            
                return Response(CommentSerialzer(obj,context={'request':request}).data)
            return Response(_('This field should not be left blank'),status=status.HTTP_400_BAD_REQUEST)
        return Response(_('You have to be loged in to add comment'),status=status.HTTP_403_FORBIDDEN)


class EditCommentAPIView(UpdateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentAddSerialzer
    permission_classes = [permissions.IsAuthenticated,
                          IsOwnerOrAdmin,
                          SameCommentPost]


class DeleteCommentAPIView(DestroyAPIView):
    queryset = Comment.objects.all()
    permission_classes = [permissions.IsAuthenticated,
                          IsOwnerOrAdmin,
                          SameCommentPost]


class AddReplyAPIView(APIView):
    def post(self,request,*args,**kwargs):
        content = request.data.get('content')
        post = get_object_or_404(Post,slug=self.kwargs.get('slug'))
        user = request.user
        if user.is_authenticated:
            comment = get_object_or_404(Comment,pk=self.kwargs.get('pk'))
            reply = ReplyAddSerialzer(data={'content':content})
            if reply.is_valid() :
                obj = reply.save(comment=comment,post=post,user=user)
                return Response(ReplySerializer(obj,context={'request':request}).data)
            return Response(_('This field should not be left blank'),status=status.HTTP_400_BAD_REQUEST)
        return Response(_('You have to be loged in to add reply'),status=status.HTTP_403_FORBIDDEN)



class EditReplyAPIView(UpdateAPIView):
    queryset = Reply.objects.all()
    serializer_class = ReplyAddSerialzer
    permission_classes = [permissions.IsAuthenticated,
                          IsOwner,
                          SameCommentAndPost]
    lookup_url_kwarg = 'reply_id'


class DeleteReplyAPIView(DestroyAPIView):
    queryset = Reply.objects.all()
    permission_classes = [permissions.IsAuthenticated,
                          IsOwnerOrAdmin,
                          SameCommentAndPost]
    lookup_url_kwarg = 'reply_id'

    

comments/views.py
# from django.http import JsonResponse
# from django.views import generic
# from django.shortcuts import render, redirect, get_object_or_404
# from comments.forms import CommentForm
# from django.contrib import messages
# from django.contrib.auth.decorators import login_required
# from django.urls import reverse
# from django.utils.safestring import mark_safe

# from posts.models import Post
# from comments.models import Comment, Reply


# COMMENT_MESSAGE = ''' 
#     <p>
#             Sorry You have to be logged in to be able to add comment please login
#     </p>  

#     '''

# SUCCESS_ADDCOMMENT_MESSAGE = 'Your comment has been added '
# SUCCESS_EDITCOMMENT_MESSAGE = 'Your comment has been modified'
# SUCCESS_DELETECOMMENT_MESSAGE = 'Your comment has been deleted'

# SUCCESS_ADDREPLY_MESSAGE = 'Your reply has been added '
# SUCCESS_EDITREPLY_MESSAGE = 'Your reply has been modified'
# SUCCESS_DELETEREPLY_MESSAGE = 'Your reply has been deleted'


# @login_required
# def add_comment_view(request, post_slug):
#     post = get_object_or_404(Post, slug=post_slug)
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.instance
#             comment.user = request.user
#             comment.post = post
#             form.save()
#             messages.success(request, SUCCESS_ADDCOMMENT_MESSAGE)
#             return redirect(post.get_absolute_url()+'#postComments')
#     return redirect(post.get_absolute_url())


# @login_required
# def edit_comment_view(request, post_slug, comment_pk):
#     user = request.user
#     comment = get_object_or_404(Comment,
#                                 id=comment_pk,
#                                 user=user)
#     if request.method == 'POST':
#         edit_form = EditCommentForm(request.POST)
#         if edit_form.is_valid():
#             content = edit_form.instance.content
#             comment.content = content
#             comment.save()
#             url = comment.post.get_absolute_url() + '#' + str(comment.id)
#             messages.success(request, SUCCESS_EDITCOMMENT_MESSAGE)
#             return redirect(url)
#     return redirect(comment.post.get_absolute_url())


# @login_required
# def delete_comment_view(request, post_slug, comment_pk):
#     user = request.user
#     comment = get_object_or_404(Comment,
#                                 id=comment_pk,
#                                 user=user,
#                                 post__slug=post_slug)
#     comment.delete()
#     messages.success(request, SUCCESS_DELETECOMMENT_MESSAGE)
#     return redirect(comment.post.get_absolute_url())


# @login_required
# def add_reply_view(request, post_slug, comment_pk):
#     user = request.user
#     post = get_object_or_404(Post, slug=post_slug)
#     comment = get_object_or_404(Comment,
#                                 id=comment_pk,
#                                 post__slug=post_slug)

#     if request.method == 'POST':
#         form = ReplyForm(request.POST)
#         if form.is_valid():
#             reply = form.instance
#             reply.user = user
#             reply.post = post
#             reply.comment = comment
#             form.save()
#             messages.success(request, SUCCESS_ADDREPLY_MESSAGE)
#             return redirect(post.get_absolute_url()+'#'+str(reply.comment.id))
#     return redirect(post.get_absolute_url())


# @login_required
# def edit_reply_view(request, post_slug, comment_pk, reply_pk):
#     user = request.user
#     reply = get_object_or_404(Reply,
#                               id=reply_pk,
#                               comment__id=comment_pk,
#                               user=user,
#                               post__slug=post_slug)

#     if request.method == 'POST':
#         edit_form = ReplyForm(request.POST)
#         if edit_form.is_valid():
#             content = edit_form.instance.content
#             reply.content = content
#             reply.save()
#             url = reply.post.get_absolute_url() + '#' + str(reply.comment.id)
#             messages.success(request, SUCCESS_EDITREPLY_MESSAGE)
#             return redirect(url)
#     return redirect(reply.post.get_absolute_url())


# @login_required
# def delete_reply_view(request, post_slug, comment_pk, reply_pk):
#     user = request.user
#     reply = get_object_or_404(Reply,
#                               id=reply_pk,
#                               comment__id=comment_pk,
#                               user=user,
#                               post__slug=post_slug)
#     reply.delete()
#     messages.success(request, SUCCESS_DELETEREPLY_MESSAGE)
#     return redirect(reply.post.get_absolute_url()+'#' + str(reply.comment.id))

comments/templates/snippets/comment.html
{% load static %}
<div class="add-comment">
  <header>
    <h4>
      Leave a comment
    </h4>
  </header>
  
  <form action="{% url 'comments:add' post_slug=obj.slug %}" method='post' id="commentsForm" class="commenting-form">
    <div class="row">
      <div class="form-group col-md-12">
        {% csrf_token %}
        {{form}}
      </div>
      <div class="form-group col-md-12">
        <button type="submit" class="my-button">Add</button>
      </div>
    </div>
  </form>
</div>

<div class="post-comments" id="postComments">
  <header id='commentsHeader'>

    {% if messages %}
    {% for message in messages %}
    <div class="
              {% if message.tags %} 
                {{ message.tags }}
              {% endif %}
              {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                alert alert-warning  
              {% else %}
                alert alert-success
              {% endif %}

               alert-dismissible fade show messages
              " role="alert">

      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}

    {% endif %}

    <h4 id='postComments'>Post Comments<span class="no-of-comments">({{obj.comments_count}})</span></h3>
  </header>
  <!-- ---- -->
  
  {% for comment in obj.all_comments %}
  <div class="comment" id="{{comment.id}}">
    <div class="comment-header d-flex justify-content-between">
      <div class="user d-flex align-items-center">
        <div class="image">
          <img src="{% if comment.user.profileimage.image %}
                  {{ comment.user.profileimage.image.url }}
                  {% else %}
                  {% static 'img/python.png' %}
                  {% endif %}
          " alt="..." class="img-fluid rounded-circle"></div>
        <div class="title">
          <strong>{{comment.user.username}}</strong>
          <span class="date">{{comment.timestamp|timesince}} ago</span>
        </div>
      </div>
    </div>
    <div class="comment-body">
      <p id="comment-content-{{comment.id}}">{{comment.content}}</p>

      <!-- Comment Option -->
      <div class="row">
        {% if user == comment.user %}
        <div class="col-md-2">
          <a href="#" id="edit-{{comment.id}}" class="EditCommentBtn "> edit </a>
        </div>
        <div class="col-md-2">
          <a href="" id="delete-{{comment.id}}" class="DeleteCommentBtn "> delete </a>
        </div>
        {% endif %}
        {% if comment.replies.count > 0 %}
        <div class="col-md-2">
          <a href="" id="replies-{{comment.id}}" class="repliesBtn "> <span>replies {{comment.replies.count}}</span>
          </a>
        </div>
        {% endif %}
        <div class="col-md-3">
          <a href="" id="add-reply-{{comment.id}}" class="addReplyBtn "> add reply </a>
        </div>

      </div>
      <!-- ================================================================ -->

      <!-- Comment Options Dev Section -->
        {% if user == comment.user %}
        <!-- Edit Div -->
        <div class="editDiv" id='editDiv-{{comment.id}}'>
          <br>
          <form action="{% url 'comments:edit' post_slug=comment.post.slug comment_pk=comment.id %}" method="post"
            id="editForm-{{comment.id}}">
            {% csrf_token %}
            {{editform}}
            <br />
            <button type="submit" class="btn btn-dark">Edit</button>

          </form>
        </div>
        <!-- ============================================ -->

      <!-- Delete Div -->

      <div id="deleteDiv-{{comment.id}}" class="deleteDiv">
        <p class="alert alert-warning"> are you sure you want to delete your comment ??</p>
        <br>
        <a href="{% url 'comments:delete' post_slug=comment.post.slug comment_pk=comment.id %}"
          class="  btn btn-dark">delete</a>
      </div>

      {% endif %}
      <!-- ========================================================== -->
      <div id="repliesDiv-{{comment.id}}" class="replies">
        <br>
        {% for reply in comment.replies.all %}
        {% include 'snippets/reply.html' %}
        {% endfor %}
      </div>
      <div id="addReplyDiv-{{comment.id}}" class="addReply">
        <br>
        <form action="{% url 'comments:add_reply' post_slug=comment.post.slug comment_pk=comment.id %}" method="post"
          id="add-reply-{{comment.id}}">
          {% csrf_token %}
          {{replyform}}
          <br />
          <button type="submit" class="btn btn-dark">Add Reply</button>

        </form>
      </div>


      <!-- ================================================================================ -->
    </div>

  </div>
  {% endfor %}
  <!-- --- -->
</div>

comments/templates/snippets/comment2.html
{% load static %}
{% load i18n %}
<div class="add-comment">
  <header>
    <h4>
      {% trans 'Leave a comment' %} 
    </h4>
  </header>
  <div style="display:none;" 
       id ="comment-error-message">
              
  </div>  
  <form action="{% url 'comments-api:add' slug=obj.slug %}" 
        method='post' id="commentsForm" 
        class="commenting-form">
    <div class="row">
      <div class="form-group col-md-12">
        {% csrf_token %}
        {{form}}
      </div>
      <div class="form-group col-md-12">
        <button type="submit" class="my-button">
          {% trans 'Add' %}
        </button>
      </div>
    </div>
  </form>
</div>

<div class="post-comments" id="postComments">
  <header id='commentsHeader'>

    {% if messages %}
    {% for message in messages %}
    <div class="
              {% if message.tags %} 
                {{ message.tags }}
              {% endif %}
              {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                alert alert-warning  
              {% else %}
                alert alert-success
              {% endif %}

               alert-dismissible fade show messages
              " role="alert">

      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}

    <h4 id='postComments'>
         {% trans 'Comments' %}
        <span class="no-of-comments">
          (<span id="comments-count">{{obj.comments_count}}</span>)
        </span>
    </h4>
    </header>
  <!-- ---- -->
 
  <div class="comments-container" id="comments-container-id" comments-list-url={{comments_list_url}}>
  </div>
  <!-- ========= Load more comments Btn =========== -->
    <div class="row">
      <div class="col-md-12 text-center">
        <br />
        <button id='load-more-comments-btn' class="btn btn-link">
          {% trans 'Load more' %}
        </button>
      </div>
    </div>
  <!-- ================================================= -->
  
</div>

comments/templates/snippets/reply.html
<div class="comment" id="reply-{{reply.id}}">
  <div class="comment-header d-flex justify-content-between">
    <div class="user d-flex align-items-center">
      <div class="image">
        <img src="{% if user.have_image %}
                  {{ reply.user.profileimage.image.url }}
                  {% endif %}
          "  alt="..." class="img-fluid rounded-circle"></div>
      <div class="title">
        <strong>{{reply.user.username}}</strong>
        <span class="date">{{reply.timestamp|timesince}} ago</span>
      </div>
    </div>
  </div>
  
  <div class="comment-body">
    
    <p id="reply-content-{{reply.id}}">{{reply.content}}</p>
    
    <!-- Reply Option -->
        
        <div class="row">
        
        {% if user == reply.user %}
          <div class="col-md-2">
               <a href="#" id="reply-edit-{{reply.id}}" class="replyEditCommentBtn " > edit </a>
          </div>
          <div class="col-md-2">
              <a href="" id="reply-delete-{{reply.id}}"  class="replyDeleteCommentBtn " > delete </a>
          </div>
          {% endif %}

        </div>
    <!-- ================================================================ -->

    <!-- Comment Options Dev Section -->
     
      {% if user == reply.user %}
          
          <!-- Edit Div -->
              
              <div class="editDiv" id='reply-editDiv-{{reply.id}}'>
                <br>

                <form action="{% url 'comments:edit_reply' post_slug=comment.post.slug comment_pk=comment.id reply_pk=reply.id %}"
                      method="post" id="reply-editForm-{{reply.id}}" >
                      {% csrf_token %}
                      {{editform}}
                      <br />
                      <button type="submit" class="btn btn-dark">Edit reply</button>

                </form>
              </div>
          
          <!-- Delete Div -->
              <div id="reply-deleteDiv-{{reply.id}}" class="deleteDiv">
                <p class="alert alert-warning"> are you sure you want to delete your reply ??</p>
                <br>
                <a href="{% url 'comments:delete_reply' post_slug=comment.post.slug comment_pk=comment.id reply_pk=reply.id %}"
                   class=" btn btn-dark" >delete</a>
              </div>

    {% endif %}
  </div>

</div>