accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from .views import (UserLoginView, UserLogoutView,EmailActivationView,
                    UserRegistrerView,profile_view,DeleteUserView)

app_name = 'accounts'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login' ),
    path('logout/', UserLogoutView.as_view(), name='logout' ),
    path('register/', UserRegistrerView.as_view(), name='register' ),
    path('profile/<slug:user_slug>/', profile_view, name='profile' ),
    path('delete/<slug:user_slug>/', DeleteUserView.as_view(), name='delete' ),
    re_path(r'^email-confirm/(?P<key>[0-9a-zA-Z]+)/$', EmailActivationView.as_view(), name='email-activate' ),
    path('email-resend-activation/', EmailActivationView.as_view(), name='email-resend-activation' ),
    

 # password settings

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap


from .sitemaps import (StaticViewsSitemaps,
                       PostsViewsSitemap,
                       AuthorViewsSitemap,
                       CategoriesViewsSitemap)

sitemaps = {'static': StaticViewsSitemaps,
            'posts': PostsViewsSitemap,
            'author_posts': AuthorViewsSitemap,
            'cats': CategoriesViewsSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error/',TemplateView.as_view(template_name='404.html')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path(r'tinymce/', include('tinymce.urls')),
    path('mailchimp/', include('marketing.urls', namespace='mailchimp')),
    path('<slug:post_slug>/comments/',
         include('comments.urls', namespace='comments')),
    path('post-<slug:slug>/comments-api/',
         include('comments.api.urls', namespace='comments-api')),
    path('posts/', include('posts.urls', namespace='posts')),
        path('', include('main.urls', namespace='main')),
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('search/', include('search.urls', namespace='search')),



    
  
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

main/urls.py
from django.urls import path
from .views import (
                    home_page_view, AboutMeView,
                    PostsDashboard,CategoriesDashboard,
                    AboutBlogView, PrivacyPolicyView, ContactUsView,
                    authors_admin_view,confirm_author_view,
                    )

app_name = 'main'
urlpatterns = [

    path('posts-dashboard/', PostsDashboard.as_view(), name='posts-dashboard'),
    path('categories-dashboard/', CategoriesDashboard.as_view(), name='categories-dashboard'),
    path('', home_page_view, name='home'),
    path('about_me', AboutMeView.as_view(), name='about_me'),
    path('about_blog', AboutBlogView.as_view(), name='about_blog'),
    path('privacy-policy', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('contact-us', ContactUsView.as_view(), name='contact_us')

    ]


urlpatterns += [
    path('authors_admin/', authors_admin_view, name='authors_admin'),


    path('confirm-author/<slug:slug>/',
         confirm_author_view, name='confirm_author')
]

posts/urls.py
from django.urls import path

from .views import (post_detail,posts_list_view, category_post_view, authors_post_view,
                    AddPostView, AddCategoryView, EditCategoryView, EditPostView, DeletePostView,
                    )

app_name = 'posts'
urlpatterns = [
    path('', posts_list_view, name='list'),
    path('add-post/', AddCategoryView.as_view(), name='add_category'),
    path('edit-category/<slug:slug>/',
         EditCategoryView.as_view(), name='edit_category'),
    path('add-category/', AddPostView.as_view(), name='add_post'),
    path('edit-post/<slug:post_slug>/', EditPostView.as_view(), name='edit_post'),
    path('delete-post/<slug:post_slug>/',
         DeletePostView.as_view(), name='delete_post'),
    path('<slug:slug>/', post_detail, name='detail'),
    path('categories/<slug:cat_slug>/posts',
         category_post_view, name='category_posts'),
    path('author/<slug:auth_slug>/posts',
         authors_post_view, name='author_posts'),
]

templates/snippets/css_files.html
{% load static %}
  

<link rel="shortcut icon" href="#" />

<!-- Bootstrap CSS-->
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
<!-- Font Awesome CSS-->
<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/all.min.css' %}">
  
<!-- Custom icon font-->
  <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
  
<!-- Google fonts - Open Sans-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <link href="https://fonts.googleapis.com/css2?family=El+Messiri&display=swap" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css2?family=El+Messiri&family=Lalezar&display=swap" rel="stylesheet"> 
  
<!-- Fancybox-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">
  
<!-- theme stylesheet -->
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">

  <!-- Tweaks for older IEs--><!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  
  
      <link rel="stylesheet" href="{% static 'css/default.css' %}">
   
 <link rel="stylesheet" type="text/css"
         href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.css">

 
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  
   
   <!-- Offline mode -->
   
   <!-- <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}">
   <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/all.min.css' %}"> -->

   <!-- ------------------------------------------- -->
   <link rel="stylesheet" href="{% static 'css/custom.css'%}">

templates/snippets/footer.html
{% load static %}
{% load i18n %}
<footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="
          {% if not categories %}
            col-md-6
          {% else %}
            col-md-4
          {% endif %}">
        <div class="logo">
          <h6 class="text-white">{{info.name}}</h6>
        </div>
        <div class="contact-details">

          {% if info.email %}
            <p>
              <span>{% trans 'Email' %}</span>
              <a href="mailto:masterbdxteam@gmail.com">
                masterbdxteam@gmail.com
              </a>
            </p>
          {% endif %}
          
          <ul class="social-menu">
            {% if info.facebook %}
            <li class="list-inline-item">
              <a href="{{info.facebook}}"><i class="fab fa-facebook-f "></i></a>
            </li>
            {% endif %}
            {% if info.twitter %}
            <li class="list-inline-item">
              <a href="{{info.twitter}}">
                <i class="fab fa-twitter fa-w"></i>
              </a>
            </li>
            {% endif %}
            {% if info.instagram %}
              <li class="list-inline-item ">
                <a href="{{info.instagram}}">
                  <i class="fab fa-instagram "></i>
                </a>
              </li>
            {% endif %}
            <!-- <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li> -->
            <!-- <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li> -->
          </ul>
        </div>
      </div>

      <div class="
          {% if not categories %}
            col-md-6
          {% else %}
            col-md-4
          {% endif %}">

        <div class="menus d-flex">
          <ul class="list-unstyled">
            {% if request.user.is_authenticated %}
            <li> 
              <a href="{% url 'account:profile' user_slug=request.user.slug %}">
                {% trans 'My Account' %}
              </a>
            </li>
            {% else %}
            <li> <a href="{% url 'account:login'  %}">
              {% trans 'Login' %}
              </a>
            </li>
            <li> 
              <a href="{% url 'account:register' %}">
                {% trans 'Register' %}
              </a>
            </li>
            {% endif %}
            <li> <a href="{% url 'main:contact_us' %}"> 
              {% trans 'Contact Us' %} </a>
            </li>
          </ul>
          <ul class="list-unstyled">
            <li> <a href="{% url 'main:about_blog' %}"> 
              {% trans 'About Blog' %} 
            </a></li>
            <li> 
                <a href="{% url 'main:about_me' %}"> 
                  {% trans 'About Me' %} 
                </a>
              </li>
            <li> <a href="{% url 'main:privacy_policy' %}"> 
              {% trans 'Privacy & Policy' %} </a></li>
          </ul>
        </div>
      </div>
      {% if categories %}
      <div class="col-md-4 ">
        <div class="footer-cats">
          <div class="cat-heading">
            <h6>{% trans 'Categories' %}</h6>
          </div>
          {% for cat in categories %}

          <div class="cat">
            <a href="{% url 'posts:category_posts' cat_slug=cat.slug %}"> {{cat.title|capfirst}} </a>
          </div>
          {% endfor %}

        </div>


      </div>

      {% endif %}
    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>
          {% trans '2019. All rights reserved for Masterbdx team' %}
          &copy;
          </p>
        </div>
        <div class="col-md-6 text-right">
          <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
            <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/snippets/javaScriptFiles.html
{% load static %}

<!-- JavaScript files-->

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
		integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
		crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"> </script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>

<script src="{% static 'js/front.js' %}"></script>

<script src="{% static 'js/cropper.min.js' %}" type="text/javascript"></script>
<script async defer src="https://assets.pinterest.com/js/pinit.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js" type="text/javascript"></script>

<script src="{% static 'js/wow.min.js' %}" type="text/javascript"></script>
<script>
              new WOW().init();
              </script>


<!-- Offline mode  -->

<!-- <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
<script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/jquery-cropper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/cropper.min.js' %}" type="text/javascript"></script> 
<script src="{% static 'js/jquery-cropper.min.js' %}" type="text/javascript"></script> -->

    <!-- ---------------------------------------------------------------- -->

<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>

templates/snippets/navbar.html
{% load i18n %}
{% load hosts %}
<!-- Main Navbar-->
<nav class="navbar navbar-expand-lg">
  <div class="search-area">
    <div class="search-area-inner d-flex align-items-center justify-content-center">
      <div class="close-btn">
        <i class="icon-close"></i>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="col-md-8">
          <form action="{% url 'search:posts' %}">
            <div class="form-group">
              <input type="search" name="q" id="search" 
              placeholder="{% trans 'What are you looking for ?' %}">
              <button type="submit" class="submit"><i class="icon-search-1"></i></button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <!-- Navbar Brand -->
    <div class="navbar-header d-flex align-items-center justify-content-between">
      <!-- Navbar Brand -->
      <a href="{% url 'main:home' %}" class="navbar-brand">
      
        {{info.name}}
       
      </a>
      <!-- Toggle Button-->
      <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse"
        aria-expanded="false" aria-label="Toggle navigation"
        class="navbar-toggler"><span></span><span></span><span></span></button>
    </div>
    <!-- Navbar Menu -->
    <div id="navbarcollapse" class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="{% url 'main:home' %}" class="nav-link ">
          <i class="fa fa-home fa-lg"></i> 
          {% trans 'Home' %}
        </a>
        </li>
        <li class="nav-item"><a href="{% url 'posts:list' %}" class="nav-link ">
          <i class="fab fa-blogger fa-lg"></i> 
          {% trans 'Blog' %}
        </a>
        </li>
        <li class="nav-item"><a href="{% url 'main:contact_us' %}" class="nav-link ">
          
          <i class="fas fa-envelope fa-lg"></i> 
         {% trans 'Contact' %}
        </a>
        </li>

        {% if request.user.is_authenticated %}    
           
        <!-------------------- Admin Dropdown ------------------>
        {% if request.user.is_admin %}
        <li class="nav-item dropdown">
          
          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          
         {% trans 'Admin' %}      
        </a>
        <div class="dropdown-menu" 
             aria-labelledby="navbarDropdown"
             style="min-width: 12rem;"
             >
          <a class="dropdown-item" href="{% url 'main:authors_admin' %}">
            {% trans 'Authors Dashboard' %}
          </a>
          <a class="dropdown-item" href="{% url 'admin:index' %}">
            {% trans  'Ultimate Dashboard' %}
          </a>
          </div>
        </li>
        {% endif %}

  <!-------------- Dashboard Dropdown -------------- -->
    {% if request.user.is_author  %}    
        <li class="nav-item dropdown">

          <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            {% trans 'Dashboard' %}
          </a>
          <div class="dropdown-menu" 
               style=" min-width: 8rem; " 
                aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'main:categories-dashboard' %}">
              {% trans 'Categories' %}
            </a>
            <a class="dropdown-item" href="{% url 'main:posts-dashboard' %}">
              {% trans 'Posts' %}
            </a>


          </div>

        </li>
    {% endif %}
  <!-- -------------------------------------------------------------- -->
        
    <li class="nav-item dropdown">
      <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
      <i class="fa fa-user fa-lg"></i>     
      {{request.user.username|capfirst}}
      <!-- <div class="profile-img">

      </div>      -->
    </a>
    <div class="dropdown-menu"
         aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{% url 'account:profile' user_slug=request.user.slug %}">
        {% trans 'Profile' %}
      </a>
        <a class="dropdown-item" href="{% url 'account:logout' %}">
          {% trans 'Logout' %}
        </a>
    </li>
   
  {% else %}
        <li class="nav-item">
          <a href="{% url 'account:login' %}" class="nav-link ">
            <i class="fas fa-sign-in-alt fa-lg"></i>
          {% trans 'Login' %}
        </a>
        </li>
        <li class="nav-item"><a href="{% url 'account:register' %}" class="nav-link ">
          <i class="fas fa-user-plus fa-lg"></i>
          {% trans 'Register' %}
        </a>
        </li>
        {% endif %}

      </ul>
      <div class="navbar-text"><a href="#" class="search-btn">
        <i class="icon-search-1"></i></a></div>

    </div>
  </div>
</nav>