blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap


from .sitemaps import (StaticViewsSitemaps,
                       PostsViewsSitemap,
                       AuthorViewsSitemap,
                       CategoriesViewsSitemap)

sitemaps = {'static': StaticViewsSitemaps,
            'posts': PostsViewsSitemap,
            'author_posts': AuthorViewsSitemap,
            'cats': CategoriesViewsSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error/',TemplateView.as_view(template_name='404.html')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path(r'tinymce/', include('tinymce.urls')),
    path('mailchimp/', include('marketing.urls', namespace='mailchimp')),
    path('<slug:post_slug>/comments/',
         include('comments.urls', namespace='comments')),
    path('post-<slug:slug>/comments-api/',
         include('comments.api.urls', namespace='comments-api')),
    path('posts/', include('posts.urls', namespace='posts')),
        path('', include('main.urls', namespace='main')),
    path('account/', include('accounts.urls', namespace='account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('search/', include('search.urls', namespace='search')),



    
  
    ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

main/urls.py
from django.urls import path
from .views import (
                    home_page_view, AboutMeView,
                    PostsDashboard,CategoriesDashboard,
                    AboutBlogView, PrivacyPolicyView, ContactUsView,
                    authors_admin_view,confirm_author_view,
                    )

app_name = 'main'
urlpatterns = [

    path('posts-dashboard/', PostsDashboard.as_view(), name='posts-dashboard'),
    path('categories-dashboard/', CategoriesDashboard.as_view(), name='categories-dashboard'),
    path('', home_page_view, name='home'),
    path('about_me', AboutMeView.as_view(), name='about_me'),
    path('about_blog', AboutBlogView.as_view(), name='about_blog'),
    path('privacy-policy', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('contact-us', ContactUsView.as_view(), name='contact_us')

    ]


urlpatterns += [
    path('authors_admin/', authors_admin_view, name='authors_admin'),


    path('confirm-author/<slug:slug>/',
         confirm_author_view, name='confirm_author')
]

posts/urls.py
from django.urls import path

from .views import (post_detail,posts_list_view, category_post_view, authors_post_view,
                    AddPostView, AddCategoryView, EditCategoryView, EditPostView, DeletePostView,
                    )

app_name = 'posts'
urlpatterns = [
    path('', posts_list_view, name='list'),
    path('add-post/', AddCategoryView.as_view(), name='add_category'),
    path('edit-category/<slug:slug>/',
         EditCategoryView.as_view(), name='edit_category'),
    path('add-category/', AddPostView.as_view(), name='add_post'),
    path('edit-post/<slug:post_slug>/', EditPostView.as_view(), name='edit_post'),
    path('delete-post/<slug:post_slug>/',
         DeletePostView.as_view(), name='delete_post'),
    path('<slug:slug>/', post_detail, name='detail'),
    path('categories/<slug:cat_slug>/posts',
         category_post_view, name='category_posts'),
    path('author/<slug:auth_slug>/posts',
         authors_post_view, name='author_posts'),
]

main/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from tinymce import HTMLField

from .utils import get_image_name


class BlogInfo(models.Model):
    name = models.CharField(max_length=200,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    
    facebook = models.URLField(null=True,blank=True)
    twitter = models.URLField(null=True,blank=True)
    instagram = models.URLField(null=True,blank=True)
    
    timestamp = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        verbose_name = _('Blog Info')
        verbose_name_plural = _('Blog Info')

    def __str__(self):
        return self.name



class MianImage(models.Model):
    image = models.ImageField(upload_to=get_image_name)
    content = HTMLField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        verbose_name = _('Mian Image')
        verbose_name_plural = _('Main Images')

    def safe_content(self):
        return mark_safe(self.content)




class AboutMe(models.Model):
    overview = models.TextField(blank=True, null=True)
    content = HTMLField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        verbose_name = _('About Us')
        verbose_name_plural = _('About Us')

    def safe_content(self):
        return mark_safe(self.content)


class AboutBlog(models.Model):
    overview = models.TextField(blank=True, null=True)
    content = HTMLField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        verbose_name = _('About Blog')
        verbose_name_plural = _('About Blog')
        

    def safe_content(self):
        return mark_safe(self.content)


class PrivacyPolicy(models.Model):
    overview = models.TextField(blank=True, null=True)
    content = HTMLField(blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        verbose_name = _('Privacy and Policy')
        verbose_name_plural = _('Privacy and Policy')

    def safe_content(self):
        return mark_safe(self.content)

main/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import AboutMe, AboutBlog, PrivacyPolicy

class ContactForm(forms.Form):
    name = forms.CharField(label=_('name'),widget=forms.TextInput())
    email = forms.EmailField(label=_('email'),widget=forms.TextInput())
    subject = forms.CharField(label=_('subject'),widget=forms.TextInput())
    message = forms.CharField(label=_('message'),widget=forms.Textarea())

    

class AboutMeForm(forms.ModelForm):
    class Meta:
        model = AboutMe
        fields = ['overview', 'content']


class AboutBlogForm(forms.ModelForm):
    class Meta:
        model = AboutBlog
        fields = ['overview', 'content']


class PrivacyPolicyForm(forms.ModelForm):
    class Meta:
        model = PrivacyPolicy
        fields = ['overview', 'content']

main/views.py
from django.shortcuts import render, reverse, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy, reverse
from django.conf import settings

from django.views.generic import (
        TemplateView, FormView, ListView,
        CreateView, UpdateView, DeleteView
        )
from django.views import generic

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.utils.translation import ugettext as _
from django.db.models import Q

from .forms import ContactForm

from posts.utils import date_capture
from posts.models import Post, Author, Category
from .models import AboutMe, AboutBlog, PrivacyPolicy,MianImage
from .mixins import AuthorRequiredMixin, AuthorCheckMixin,AdminRequiredMixin
from blog.decorators import super_user_only

from .forms import AboutBlogForm, AboutMeForm, PrivacyPolicyForm
import string


User = get_user_model()

def home_page_view(request):
    main_obj = MianImage.objects.last()
    featured_posts = Post.objects.featured()[:3].select_related('author__user',
                                                                'author__user__profileimage')
    latest_posts = Post.objects.all().prefetch_related('categories',)[:3]
    context = {'featured_posts': featured_posts,
               'latest_posts': latest_posts,
               'obj':main_obj
               
               }
    return render(request, 'main/home.html', context)



class AboutMeView(ListView):
    template_name = 'info/about_me.html'

    context_object_name = 'privacy'

    def get_queryset(self):
        qs = AboutMe.objects.all().last()
        return qs


class AboutBlogView(ListView):
    template_name = 'info/about_blog.html'

    context_object_name = 'about_blog'

    def get_queryset(self):
        qs = AboutBlog.objects.all().last()
        return qs


class PrivacyPolicyView(ListView):
    template_name = 'info/privacy_policy.html'
    context_object_name = 'privacy'

    def get_queryset(self):
        qs = PrivacyPolicy.objects.all().last()
        return qs


class ContactUsView(FormView):
    form_class = ContactForm
    template_name = 'info/contact_us.html'
    success_url = reverse_lazy('main:contact_us')

    def form_valid(self, form):
        subject = form.cleaned_data.get('name')
        from_email = form.cleaned_data.get('email')
        to_email = getattr(settings, 'DEFAULT_FROM_EMAIL')
        message = form.cleaned_data.get('message')
        context = {'name': subject, 'email': from_email, 'message': message, }
        txt_ = get_template('snippets/message.txt').render(context)
        html_ = get_template(
            'snippets/html_message.html').render(context)
        send_mail(
            subject,
            txt_,
            from_email,
            [to_email, ],
            html_message=html_,
            fail_silently=False
        )
        messages.add_message(self.request, messages.SUCCESS,
                             _('your message has been sent'))
        return redirect('main:contact_us')


class PostsDashboard(LoginRequiredMixin, AuthorRequiredMixin, generic.ListView):
    template_name = 'main/dashboards/posts.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 15

    def get_queryset(self):
        q = self.request.GET.get('q')    
        author = self.request.user.author
        
        if q:
            date, exists = date_capture(q)
            if exists:
                year, month, day = date.split('-')
                if int(year) == 0 or int(month) == 0 and int(day) == 0:
                    date = '2000-12-12'
            else:
                date = '2000-12-12'

            filters = Q(title__icontains=q) | Q(content__icontains=q) |Q(timestamp=date) | Q(slug__exact=q)
            qs = super().get_queryset().filter(author=author).filter(filters).order_by('slug')
        else:
            qs = super().get_queryset().filter(author=author).order_by('slug')
        return qs


class CategoriesDashboard(LoginRequiredMixin,generic.ListView):
    template_name = 'main/dashboards/categories.html'
    model = Category
    context_object_name = 'cates'


@login_required
@super_user_only
def authors_admin_view(request):
    page_var = 'page'
    page = request.GET.get(page_var, 1)
    
    current_page = User.objects.qs_paginator(page=page)

    context = {'page_obj': current_page,
               'page_var': page_var,
               }

    return render(request, 'main/authors_admin.html', context)


@login_required
@super_user_only
def confirm_author_view(request, slug):
    confirm = request.POST.get('confirm')
    status = request.POST.get('status', _('create'))
    username = User.objects.filter(slug=slug).values(
        'username').first()['username']

    if confirm:
        user = User.objects.filter(slug=slug).first()
        if user.is_author:
            status = _('deleted')
            author = Author.objects.filter(user__slug=slug).first().delete()
            user.is_author = False
            
        else:
            status = _('created')
            user.is_author = True
            author = Author.objects.create(user=user)        
        user.save()
        messages.add_message(request, messages.SUCCESS,
                             _('You have successfuly {} Author for {} ').format(status, username).upper())
        return redirect('main:authors_admin')
    return render(request, 'main/confirm_author.html', {"status": status, 'username': username})

main/templates/main/authors_admin.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
{% trans 'Authors Dashboard' %}
{% endblock %}

{% block content %}
{% load static %}


<div class='container'>  
  <div class='row '>
    <div class="col-md-7 m-auto ">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.level_tag}} alert-dismissible fade show" role="alert">
            <p{% if message.tags %} class="{{ message.tags }} text-center" {% endif %}>{{ message }}</p>
                {% endfor %}

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        {% endif %}
  </div>
    <div class='col-md-6 m-auto auth text-center'>
      <h2 class="mt-4 mb-4 pb-3 ">
        {% trans 'Authors Dashboard' %}
      </h2>
    </div>
    <div class='col-md-8 m-auto'>
      {% include 'snippets/search_users.html' %}
    </div>
    <div class="col-md-10 m-auto">
      {% if page_obj %}
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">{% trans 'Id' %}</th>
            <th scope="col">{% trans 'Username' %}</th>
            <th scope="col">{% trans 'Slug' %}</th>
            <th scope="col">{% trans 'Email' %}</th>
            <th scope="col">{% trans 'Status' %}</th>
          </tr>
        </thead>
        <tbody>
          {% for user in page_obj.object_list %}
          <tr>
            <th scope="row">{{user.id}}</th>
            <td>{{user.username}}</td>
            <td>{{user.slug}}</td>
            <td>{{user.email}}</td>
            <td>
              <form method='post' action="{% url 'main:confirm_author' slug=user.slug %}">
                {% csrf_token %}
                <input type="hidden" name='status' 
                       value="
                       {% if user.is_author %}
                          {% trans 'deleted' %} 
                       {% else %} 
                          {% trans 'created' %}
                        {% endif %}" />
                <button user-slug='{{user.slug}}' id='author-control' 
                                  class="my-button">
                  {% if user.is_author %}
                  {% trans 'Remove Author' %}
                  {% else %}
                  {% trans 'Add Author' %}
                  {% endif %}
                </button>
              </form>

            </td>
          </tr>
          {% endfor %}

        </tbody>

      </table>
      {% else %}
      <div class='col-lg-12 text-center '>
        {% if request.GET.q %}
        <h2> Could not find any results for {{request.GET.q}} </h2>
        {% else %}
        <h2> There are no users </h2>
        {% endif %}
      </div>
      {% endif %}
    </div>

    {% if page_obj %}
    <div class='col-lg-12 '>
      <!-- Pagination -->
      {% include 'snippets/paginator.html' with page_obj=page_obj page_var=page_var beta=request.GET.beta %}
      <br>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

main/templates/main/categories.html
{% extends 'base.html' %}
{% block title %}Catgories Dashboard{% endblock %}
{% block  content %}
{% load static %}

<div class="container dash-board">
  <div class="row">
    <div class="col-sm-10 offset-md-1 text-center">
      <h1 class="display-4"><br>Catgories Dashboard<br>
        <hr>
      </h1>
    </div>

    <div class="col-sm-10 offset-md-1">
      <h2>Categories</h2>
      <p class=""><i class="fa fa-plus"></i> To add new Category</p>
      <a class="btn btn-info" href="{% url 'posts:add_category' %}">Add</a>
    </div>
    <div class="col-sm-10 offset-md-1">
      <br />
      {% if cates %}
      <table class="table">

        <thead class="thead-dark">
          <tr style="border-radius: 6px">
            <th scope="col">Title</th>
            <th scope="col">Created At</th>
            <th scope="col">

              ###
            </th>
          </tr>
        </thead>
        <tbody>
          {% for cate in cates %}
          <tr>
            <th scope="row">{{cate.title|capfirst}}</th>
            <td>{{cate.timestamp}}</td>
            <td class="">
              <a href="{% url 'posts:edit_category' slug=cate.slug %}" class='btn'>
                Edit
              </a>

            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
      {% else %}
      <p class="das-par text-center"> There are No Categories</p>
      {% endif %}

    </div>

  </div>
</div>
{% endblock %}

main/templates/main/confirm_author.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Confirm Author' %}
{% endblock  %}
  
{% block content %}
{% load static %}

<div class='container'>
  <div class='row '>
    <div class='text-center col-md-6 auth m-auto'>

      <h2 class=" mt-5 ">
        {% trans 'Confirm Author' %}
        
      </h2>
    </div>
      <div class="col-md-8 m-auto">
      <p class='text-center lead'>
        يرجى التأكيد للقيام ب
        {{status}}
        المؤلف للمستخدم 
        {{username}}
      </p>
      <form class='text-center' method='post'>
        {% csrf_token %}
        <input type="hidden" name='confirm' value='True' />
        <button class='btn btn-dark '>{{status|upper}}</button>
        <br>
        <br>
      </form>
    </div>
  </div>
 
</div>

{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Home' %}{% endblock %}
{% block content %}
{% load static %}

<!-- Hero Section-->
<section style="
    background: url({% if obj %}
                    {{obj.image.url}}
                    {% else %}
                    {% static 'img/blog.png'%}
                    {% endif %}); background-size: cover; background-position: center center"
  class="hero">

  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 m-auto">
        {% if obj.content %}
        <h1 class="home-heading" style="">
        {{obj.safe_content}}
        </h1>
        {% endif %}
      </div>
    </div>

  </div>
</section>


{% if featured_posts.exists %}
{% include 'main/snippets/featured_posts.html' %}

<!-- Divider Section-->
<div class="divider">
</div>

{% endif %}
{% if latest_posts %}

<!-- Latest Posts -->
<section style="padding:50px 0" class="latest-posts ">
  <div class="container">
    <header class="main-header">
      <h2>{% trans 'Latest posts from the blog' %} </h2>

    </header>
    <div class="row">
      {% for obj in latest_posts %}
      <div class="post col-md-4 wow fadeInLeft">
        <div class="post-thumbnail">
          <a href="{% url 'posts:detail' slug=obj.slug %}">

            <img width="350" height="180" src="{% if  obj.thumbnail.url %}
                          {{obj.thumbnail.url}}
                      {% else %}
                          {% static 'img/default_placeholder.png' %}
                      {% endif %}
                          " alt="..." class="img-fluid img-thumbnail">
          </a>
        </div>
        <div class="post-details">
          <div class="post-meta d-flex justify-content-between">
            <div class="date">{{obj.timestamp}}</div>
            <div class="category">
              {% for category in obj.categories.all %}
              <a href="{% url 'posts:category_posts' cat_slug=category.slug %}">{{category.title}}</a>
              {% endfor %}
            </div>
          </div>
          <a href="{{obj.get_absolute_url}}">
            <h3 class="h4">{{obj.title}}</h3>
          </a>
          <p class="text-muted"> {{obj.overview|truncatewords:25}} </p>
        </div>
      </div>
      {% endfor %}


    </div>
  </div>
</section>
{% endif %}

{% endblock %}